POST https://deploy-agent-tutorial-production.up.railway.app/conversations

###

POST https://deploy-agent-tutorial-production.up.railway.app/conversations/conv_6968f5663a908194a694a8feeab561080a4f5905e234d0a1/message
Content-Type: application/json

{
    "question": "What is the first question i asked?"
}

###

POST https://deploy-agent-tutorial-production.up.railway.app/conversations/conv_6968f5663a908194a694a8feeab561080a4f5905e234d0a1/message/stream
Content-Type: application/json

{
    "question": "What is the first question i asked?"
}


curl -N -X POST https://deploy-agent-tutorial-production.up.railway.app/conversations/conv_6968f5663a908194a694a8feeab561080a4f5905e234d0a1/message/stream \
-H "Content-Type: application/json" \
-d '{"question": "대한민국의 GDP 순위는?"}'


curl -N -X POST https://deploy-agent-tutorial-production.up.railway.app/conversations/conv_6968f5663a908194a694a8feeab561080a4f5905e234d0a1/message/stream/all \
-H "Content-Type: application/json" \
-d '{"question": "대한민국의 GDP 순위는?"}'